ALTER TABLE [dbo].[ClientISPDetail] ADD [ResourcesExplain] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [BarriersExplain] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [AssNumDesc] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [FormDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [CAChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [CAUpdateChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [PsychEvalChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [OtherChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjStartDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [PerNameWillDesc] [varchar](250) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GuardWillNameDesc] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [NotClinChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [OtherStatDesc] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalTargetDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjTargetDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [AssessKey] [int] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalActiveChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalNewChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalDiscontinuedChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalCompChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalRevisedChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [EvidenceRationale] [text] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalStatusKey] [int] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalDiscontDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [GoalCompDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjStatusKey] [int] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [AssessKey2] [int] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [AssessKey3] [int] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [DateProgressNote] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ProgNoteNAChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjActiveChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjNewChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjDiscontinuedChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjDiscontDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjCompChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjCompDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjRevisedChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjEvidenceRationale] [text] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [DateProgressNoteObj] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ProgNoteNAObjChk] [tinyint] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [AssessmentDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [AssessmentKey] [int] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [OptionsMeetGoalDesc] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [OptionsSelectDesc] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [TasksDesc] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [RespPersonDesc] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [TargetStartDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [TargetEndDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [TaskStatusDesc] [varchar](50) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [ObjProblemDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [OptionSelectedYNKey] [char](1) NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [RevisedTargetDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [RevisedObjectiveTargetDate] [datetime] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [StrengthExp] [text] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [CultureExp] [text] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [BrainStormExp] [text] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [NeedsAddPriorityExp] [text] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [NeedsAddRegExp] [text] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [LifeDomainExp] [text] NULL
ALTER TABLE [dbo].[ClientISPDetail] ADD [MeasurementStat] [text] NULL